x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    platform: linux/amd64
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    platform: linux/amd64
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=judge0pass
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    platform: linux/amd64
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
